/* eslint-disable @next/next/no-img-element */
/**
 * Lifted from the Devsync template — its own markup, laid out by its own
 * stylesheet (styles/devsync.css). The copy, images, links and accent colour
 * are Nelson's; the structure is the template's.
 *
 * Generated by the lift script. Edit the script, not this file.
 */
export default function HeroSpacer() {
  return (
    <>
<div className="framer-1nuza4i-container"><div></div></div>
    </>
  );
}
