/* eslint-disable @next/next/no-img-element */
/**
 * Lifted from the Devsync template — its own markup, laid out by its own
 * stylesheet (styles/devsync.css). The copy, images, links and accent colour
 * are Nelson's; the structure is the template's.
 *
 * Generated by the lift script. Edit the script, not this file.
 */
export default function Sprite() {
  return (
    <>
<div id="svg-templates" style={{position: "absolute", overflow: "hidden", bottom: "0", left: "0", width: "0", height: "0", zIndex: "0", contain: "strict"} as React.CSSProperties} aria-hidden="true"><svg viewBox="0 0 5 10" overflow="visible" id="svg1683248830_349"><path d="M 5 0 L 0 5 L 5 10" fill="transparent" stroke={"var(--token-bb0c0bd9-9918-415b-81a2-622ee217b736, rgb(17, 17, 17)) /* {\"name\":\"BG -01\"} */"} strokeLinecap="round" strokeLinejoin="round" />
</svg><svg viewBox="0 0 5 10" overflow="visible" id="svg664901113_349"><path d="M 0 0 L 5 5 L 0 10" fill="transparent" stroke={"var(--token-bb0c0bd9-9918-415b-81a2-622ee217b736, rgb(17, 17, 17)) /* {\"name\":\"BG -01\"} */"} strokeLinecap="round" strokeLinejoin="round" />
</svg><svg viewBox="0 0 41.5 43.5" overflow="visible" id="svg-1334880870_404"><path d="M 17 0 L 25 0 L 24 16 L 37.5 8 L 41.5 14.5 L 27.5 22 L 41.5 29 L 37.5 37 L 24 27.5 L 25 43.5 L 17 43.5 L 17.5 27.5 L 4 36.5 L 0 29 L 14 22 L 0 14.5 L 4 7 L 17 16 Z" fill="var(--token-be169701-d49d-4dc1-9412-4e8be21feaa1, var(--accent))" opacity="0.3" />
</svg><svg viewBox="0 0 17 14" overflow="visible" id="svg579187597_622"><g><path d="M 3.144 2.728 L 0 6.819 L 3.144 10.91" fill="transparent" stroke="rgb(255,255,255)" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="" />
<path d="M 13.679 10.909 L 17 6.818 L 13.679 2.727" fill="transparent" stroke="rgb(255,255,255)" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="" />
<path d="M 9.956 0 L 6.525 14" fill="transparent" stroke="rgb(255,255,255)" strokeLinecap="round" data-stroke-miterlimit="10" strokeDasharray="" /></g></svg><svg width="146" height="116" viewBox="-1 -1 146 116" fill="none" id="svg689205295_1190"><path d="M135.133 0V24.1495H121.301C110.424 24.1495 104.985 29.595 104.985 40.486V51.8505H111.015C120.473 51.8505 128.276 54.6916 134.424 60.3738C140.808 66.0561 144 73.2773 144 82.0374C144 91.5078 140.808 99.2025 134.424 105.121C128.276 111.04 120.473 114 111.015 114C101.32 114 93.399 111.04 87.2512 105.121C81.1034 98.9657 78.0296 90.7975 78.0296 80.6168V39.7757C78.0296 13.2586 91.2709 0 117.754 0H135.133ZM57.1034 0V24.1495H43.2709C32.3941 24.1495 26.9557 29.595 26.9557 40.486V51.8505H32.9852C42.4434 51.8505 50.2463 54.6916 56.3941 60.3738C62.7783 66.0561 65.9704 73.2773 65.9704 82.0374C65.9704 91.5078 62.7783 99.2025 56.3941 105.121C50.2463 111.04 42.4434 114 32.9852 114C23.2906 114 15.3695 111.04 9.22168 105.121C3.07389 98.9657 0 90.7975 0 80.6168V39.7757C0 13.2586 13.2414 0 39.7241 0H57.1034Z" fill="url(#svg689205295_1190_paint0_linear_14518_4003)" />
<defs><linearGradient id="svg689205295_1190_paint0_linear_14518_4003" x1="72" y1="-150" x2="72" y2="114" gradientUnits="userSpaceOnUse"><stop stopColor="#7AF298" /><stop offset="1" stopColor="#7AF298" stopOpacity="0" /></linearGradient></defs></svg><svg data-display="block" role="presentation" viewBox="0 0 24 24"><path d="M 8.5 8.5 L 8.5 0 L 0 0" fill="transparent" height="8.5px" id="HD3EjFRmq" strokeDasharray="" strokeLinecap="round" strokeLinejoin="round" strokeWidth="var(--1335ju, 1.5)" stroke="var(--18mrqx2, rgb(0, 0, 0))" transform="translate(8.75 6.75)" width="8.5px" />
<path d="M 10.25 0 L 0 10.25" fill="transparent" height="10.25px" id="I0i29aTCw" strokeDasharray="" strokeLinecap="round" strokeLinejoin="round" strokeWidth="var(--1335ju, 1.5)" stroke="var(--18mrqx2, rgb(0, 0, 0))" transform="translate(6.75 7)" width="10.25px" />
</svg></div>
    </>
  );
}
