/* eslint-disable @next/next/no-img-element */
/**
 * Lifted verbatim from the Fastfolio template: the same markup and the same
 * class names, so `styles/fastfolio.css` (also taken from the template) lays it
 * out identically. Only the copy, the images and the accent colour differ.
 *
 * Generated — see the lift script in the project notes; edit the data, not this.
 */
export default function ExperienceSection() {
  return (
    <section className="framer-xelcrv" id="experience"><div className="framer-limzcx"><div className="framer-zncqi4"><div className="framer-8vlj11-container" data-reveal="true"><div className="framer-OLJCl framer-GVdQe framer-1ruw5ua framer-v-1ruw5ua" data-framer-name="Default" style={{backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div className="framer-l21fbl" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-1c49kmm" data-styles-preset="NoguLCmHa" dir="auto">EXPERIENCE</p></div></div></div><div className="framer-o7a2t9" data-framer-component-type="RichTextContainer" style={{transform: "none"} as React.CSSProperties}><h2 className="framer-text framer-styles-preset-wj1llc" data-styles-preset="fQF7LPveS" dir="auto" style={{"--framer-text-alignment": "center"} as React.CSSProperties}>
<strong className="framer-text"><span style={{whiteSpace: "nowrap"} as React.CSSProperties}><span style={{display: "inline-block"} as React.CSSProperties} data-char={0}>W</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={1}>h</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={2}>e</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={3}>r</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={4}>e</span></span>{" "}<span style={{whiteSpace: "nowrap"} as React.CSSProperties}><span style={{display: "inline-block"} as React.CSSProperties} data-char={5}>I</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={6}>’</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={7}>v</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={8}>e</span></span>{" "}<span style={{whiteSpace: "nowrap"} as React.CSSProperties}><span style={{display: "inline-block"} as React.CSSProperties} data-char={9}>W</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={10}>o</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={11}>r</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={12}>k</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={13}>e</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={14}>d</span></span></strong></h2></div><div className="framer-nilvrg" data-framer-component-type="RichTextContainer" data-reveal="true"><p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "center"} as React.CSSProperties}>
Seven years of shipping production systems, and the interfaces on top of them</p></div></div><div className="framer-1ymeq7m"><div className="ssr-variant hidden-2t7pqm"><div className="framer-gjtf69-container" data-framer-name="experience card" data-reveal="true"><div className="framer-ou6pr framer-Au8L7 framer-bt7oY framer-9p2kii framer-v-9p2kii" data-framer-name="Opened" data-highlight="true" tabIndex={0} style={{backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", width: "100%", borderBottomLeftRadius: "20px", borderBottomRightRadius: "20px", borderTopLeftRadius: "20px", borderTopRightRadius: "20px"} as React.CSSProperties}>
<div className="framer-h68uep" data-framer-name="Role + Duration Wrapper"><div className="framer-17xkw30" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<h4 className="framer-text framer-styles-preset-udtsgy" data-styles-preset="d2b6kdCPr" dir="auto">Senior Software Engineer, Pandar Resources</h4></div><div className="framer-83j44z" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "right"} as React.CSSProperties}>
2026 - Present</p></div></div><div className="framer-fmtgiz" data-framer-name="Contributions Wrapper" style={{opacity: "1"} as React.CSSProperties}><div className="framer-5g7ev9" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>
<li data-preset-tag="p" className="framer-text"><p className="framer-text" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>Built the dashboards and the APIs behind them in TypeScript, React and NestJS</p></li></ul></div><div className="framer-1v2p1z0" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Cut average response times by 60% through connection pooling and query optimisation</p></li></ul></div><div className="framer-1ynh7ja" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Added structured logging and metrics, speeding up debugging of high-throughput services</p></li></ul></div></div><div className="framer-qipdi4" data-framer-name="Toggle Button"><svg className="framer-LIyKS framer-x60i8n" role="presentation" viewBox="0 0 24 24" style={{"--1m973uw": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--js9iwy": "2", transform: "none"} as React.CSSProperties}>
<use href="#1249959720" /></svg></div></div></div></div><div className="ssr-variant hidden-1vo249k hidden-72rtr7"><div className="framer-gjtf69-container" data-framer-name="experience card" data-reveal="true"><div className="framer-ou6pr framer-Au8L7 framer-bt7oY framer-9p2kii framer-v-1ehfzo" data-framer-name="responsive-opened" data-highlight="true" tabIndex={0} style={{backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", width: "100%", borderBottomLeftRadius: "20px", borderBottomRightRadius: "20px", borderTopLeftRadius: "20px", borderTopRightRadius: "20px"} as React.CSSProperties}>
<div className="framer-h68uep" data-framer-name="Role + Duration Wrapper"><div className="framer-17xkw30" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<h4 className="framer-text framer-styles-preset-udtsgy" data-styles-preset="d2b6kdCPr" dir="auto">Senior Software Engineer, Pandar Resources</h4></div><div className="framer-83j44z" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>
2026 - Present</p></div></div><div className="framer-fmtgiz" data-framer-name="Contributions Wrapper" style={{opacity: "1"} as React.CSSProperties}><div className="framer-5g7ev9" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>
<li data-preset-tag="p" className="framer-text"><p className="framer-text" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>Built the dashboards and the APIs behind them in TypeScript, React and NestJS</p></li></ul></div><div className="framer-1v2p1z0" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Cut average response times by 60% through connection pooling and query optimisation</p></li></ul></div><div className="framer-1ynh7ja" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Added structured logging and metrics, speeding up debugging of high-throughput services</p></li></ul></div></div><div className="framer-qipdi4" data-framer-name="Toggle Button"><svg className="framer-LIyKS framer-x60i8n" role="presentation" viewBox="0 0 24 24" style={{"--1m973uw": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--js9iwy": "2", transform: "none"} as React.CSSProperties}>
<use href="#1249959720" /></svg></div></div></div></div><div className="ssr-variant hidden-2t7pqm"><div className="framer-z8o3va-container" data-reveal="true"><div className="framer-ou6pr framer-Au8L7 framer-bt7oY framer-9p2kii framer-v-1chhkwp" data-framer-name="Closed" data-highlight="true" tabIndex={0} style={{backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", width: "100%", borderBottomLeftRadius: "20px", borderBottomRightRadius: "20px", borderTopLeftRadius: "20px", borderTopRightRadius: "20px"} as React.CSSProperties}>
<div className="framer-h68uep" data-framer-name="Role + Duration Wrapper"><div className="framer-17xkw30" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<h4 className="framer-text framer-styles-preset-udtsgy" data-styles-preset="d2b6kdCPr" dir="auto">Full Stack Engineer, ODJTech Multimedia</h4></div><div className="framer-83j44z" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "right"} as React.CSSProperties}>
2025 - 2026</p></div></div><div className="framer-fmtgiz" data-framer-name="Contributions Wrapper" data-reveal="true"><div className="framer-5g7ev9" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>
<li data-preset-tag="p" className="framer-text"><p className="framer-text" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>Shipped customer-facing interfaces in React alongside the event-driven services behind them</p></li></ul></div><div className="framer-1v2p1z0" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Implemented Redis caching that held response times steady under concurrent load</p></li></ul></div><div className="framer-1ynh7ja" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Drove reliability work: failure-mode handling and autoscaling for production stability</p></li></ul></div></div><div className="framer-qipdi4" data-framer-name="Toggle Button"><svg className="framer-LIyKS framer-x60i8n" role="presentation" viewBox="0 0 24 24" style={{"--1m973uw": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--js9iwy": "2", transform: "rotate(180deg)"} as React.CSSProperties}>
<use href="#1249959720" /></svg></div></div></div></div><div className="ssr-variant hidden-1vo249k hidden-72rtr7"><div className="framer-z8o3va-container" data-reveal="true"><div className="framer-ou6pr framer-Au8L7 framer-bt7oY framer-9p2kii framer-v-2ek0h0" data-framer-name="responsive-closed" data-highlight="true" tabIndex={0} style={{backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", width: "100%", borderBottomLeftRadius: "20px", borderBottomRightRadius: "20px", borderTopLeftRadius: "20px", borderTopRightRadius: "20px"} as React.CSSProperties}>
<div className="framer-h68uep" data-framer-name="Role + Duration Wrapper"><div className="framer-17xkw30" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<h4 className="framer-text framer-styles-preset-udtsgy" data-styles-preset="d2b6kdCPr" dir="auto">Full Stack Engineer, ODJTech Multimedia</h4></div><div className="framer-83j44z" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>
2025 - 2026</p></div></div><div className="framer-fmtgiz" data-framer-name="Contributions Wrapper" data-reveal="true"><div className="framer-5g7ev9" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>
<li data-preset-tag="p" className="framer-text"><p className="framer-text" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>Shipped customer-facing interfaces in React alongside the event-driven services behind them</p></li></ul></div><div className="framer-1v2p1z0" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Implemented Redis caching that held response times steady under concurrent load</p></li></ul></div><div className="framer-1ynh7ja" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Drove reliability work: failure-mode handling and autoscaling for production stability</p></li></ul></div></div><div className="framer-qipdi4" data-framer-name="Toggle Button"><svg className="framer-LIyKS framer-x60i8n" role="presentation" viewBox="0 0 24 24" style={{"--1m973uw": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--js9iwy": "2", transform: "rotate(180deg)"} as React.CSSProperties}>
<use href="#1249959720" /></svg></div></div></div></div><div className="ssr-variant hidden-2t7pqm"><div className="framer-1qm0shb-container" data-reveal="true"><div className="framer-ou6pr framer-Au8L7 framer-bt7oY framer-9p2kii framer-v-1chhkwp" data-framer-name="Closed" data-highlight="true" tabIndex={0} style={{backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", width: "100%", borderBottomLeftRadius: "20px", borderBottomRightRadius: "20px", borderTopLeftRadius: "20px", borderTopRightRadius: "20px"} as React.CSSProperties}>
<div className="framer-h68uep" data-framer-name="Role + Duration Wrapper"><div className="framer-17xkw30" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<h4 className="framer-text framer-styles-preset-udtsgy" data-styles-preset="d2b6kdCPr" dir="auto">Product Engineer, Unispend</h4></div><div className="framer-83j44z" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "right"} as React.CSSProperties}>
2025 - 2026</p></div></div><div className="framer-fmtgiz" data-framer-name="Contributions Wrapper" data-reveal="true"><div className="framer-5g7ev9" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>
<li data-preset-tag="p" className="framer-text"><p className="framer-text" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>Built the student wallet UI, QR-code payment flow and transaction history end to end</p></li></ul></div><div className="framer-1v2p1z0" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Designed the analytics dashboards revenue-sharing partners use day to day</p></li></ul></div><div className="framer-1ynh7ja" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Wired JWT auth and rate limiting across the campus payments ecosystem</p></li></ul></div></div><div className="framer-qipdi4" data-framer-name="Toggle Button"><svg className="framer-LIyKS framer-x60i8n" role="presentation" viewBox="0 0 24 24" style={{"--1m973uw": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--js9iwy": "2", transform: "rotate(180deg)"} as React.CSSProperties}>
<use href="#1249959720" /></svg></div></div></div></div><div className="ssr-variant hidden-1vo249k hidden-72rtr7"><div className="framer-1qm0shb-container" data-reveal="true"><div className="framer-ou6pr framer-Au8L7 framer-bt7oY framer-9p2kii framer-v-2ek0h0" data-framer-name="responsive-closed" data-highlight="true" tabIndex={0} style={{backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", width: "100%", borderBottomLeftRadius: "20px", borderBottomRightRadius: "20px", borderTopLeftRadius: "20px", borderTopRightRadius: "20px"} as React.CSSProperties}>
<div className="framer-h68uep" data-framer-name="Role + Duration Wrapper"><div className="framer-17xkw30" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<h4 className="framer-text framer-styles-preset-udtsgy" data-styles-preset="d2b6kdCPr" dir="auto">Product Engineer, Unispend</h4></div><div className="framer-83j44z" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>
2025 - 2026</p></div></div><div className="framer-fmtgiz" data-framer-name="Contributions Wrapper" data-reveal="true"><div className="framer-5g7ev9" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>
<li data-preset-tag="p" className="framer-text"><p className="framer-text" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>Built the student wallet UI, QR-code payment flow and transaction history end to end</p></li></ul></div><div className="framer-1v2p1z0" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Designed the analytics dashboards revenue-sharing partners use day to day</p></li></ul></div><div className="framer-1ynh7ja" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Wired JWT auth and rate limiting across the campus payments ecosystem</p></li></ul></div></div><div className="framer-qipdi4" data-framer-name="Toggle Button"><svg className="framer-LIyKS framer-x60i8n" role="presentation" viewBox="0 0 24 24" style={{"--1m973uw": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--js9iwy": "2", transform: "rotate(180deg)"} as React.CSSProperties}>
<use href="#1249959720" /></svg></div></div></div></div><div className="ssr-variant hidden-2t7pqm"><div className="framer-1na578a-container" data-reveal="true"><div className="framer-ou6pr framer-Au8L7 framer-bt7oY framer-9p2kii framer-v-1chhkwp" data-framer-name="Closed" data-highlight="true" tabIndex={0} style={{backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", width: "100%", borderBottomLeftRadius: "20px", borderBottomRightRadius: "20px", borderTopLeftRadius: "20px", borderTopRightRadius: "20px"} as React.CSSProperties}>
<div className="framer-h68uep" data-framer-name="Role + Duration Wrapper"><div className="framer-17xkw30" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<h4 className="framer-text framer-styles-preset-udtsgy" data-styles-preset="d2b6kdCPr" dir="auto">Full Stack Engineer, FastPay Tech</h4></div><div className="framer-83j44z" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "right"} as React.CSSProperties}>
2023 - 2024</p></div></div><div className="framer-fmtgiz" data-framer-name="Contributions Wrapper" data-reveal="true"><div className="framer-5g7ev9" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>
<li data-preset-tag="p" className="framer-text"><p className="framer-text" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>Built payment interfaces and the APIs behind them, owning both ends of the flow</p></li></ul></div><div className="framer-1v2p1z0" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Designed a real-time webhook system with delivery guarantees for payment notifications</p></li></ul></div><div className="framer-1ynh7ja" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Reduced manual reconciliation by 40% across high-volume transaction traffic</p></li></ul></div></div><div className="framer-qipdi4" data-framer-name="Toggle Button"><svg className="framer-LIyKS framer-x60i8n" role="presentation" viewBox="0 0 24 24" style={{"--1m973uw": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--js9iwy": "2", transform: "rotate(180deg)"} as React.CSSProperties}>
<use href="#1249959720" /></svg></div></div></div></div><div className="ssr-variant hidden-1vo249k hidden-72rtr7"><div className="framer-1na578a-container" data-reveal="true"><div className="framer-ou6pr framer-Au8L7 framer-bt7oY framer-9p2kii framer-v-2ek0h0" data-framer-name="responsive-closed" data-highlight="true" tabIndex={0} style={{backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", width: "100%", borderBottomLeftRadius: "20px", borderBottomRightRadius: "20px", borderTopLeftRadius: "20px", borderTopRightRadius: "20px"} as React.CSSProperties}>
<div className="framer-h68uep" data-framer-name="Role + Duration Wrapper"><div className="framer-17xkw30" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<h4 className="framer-text framer-styles-preset-udtsgy" data-styles-preset="d2b6kdCPr" dir="auto">Full Stack Engineer, FastPay Tech</h4></div><div className="framer-83j44z" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>
2023 - 2024</p></div></div><div className="framer-fmtgiz" data-framer-name="Contributions Wrapper" data-reveal="true"><div className="framer-5g7ev9" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>
<li data-preset-tag="p" className="framer-text"><p className="framer-text" style={{"--framer-text-alignment": "left"} as React.CSSProperties}>Built payment interfaces and the APIs behind them, owning both ends of the flow</p></li></ul></div><div className="framer-1v2p1z0" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Designed a real-time webhook system with delivery guarantees for payment notifications</p></li></ul></div><div className="framer-1ynh7ja" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties} data-reveal="true">
<ul className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto"><li data-preset-tag="p" className="framer-text"><p className="framer-text">Reduced manual reconciliation by 40% across high-volume transaction traffic</p></li></ul></div></div><div className="framer-qipdi4" data-framer-name="Toggle Button"><svg className="framer-LIyKS framer-x60i8n" role="presentation" viewBox="0 0 24 24" style={{"--1m973uw": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--js9iwy": "2", transform: "rotate(180deg)"} as React.CSSProperties}>
<use href="#1249959720" /></svg></div></div></div></div></div><div className="framer-19ysn0r-container" data-framer-name="Primary Button" data-reveal="true"><a className="framer-sEkee framer-GxEnY framer-16bp2hk framer-v-16bp2hk framer-1dvxmiq" data-framer-name="default" data-highlight="true" href="https://docs.google.com/" target="_blank" rel="noopener" tabIndex={0} style={{backgroundColor: "var(--token-b4d223ed-03f5-4a9b-89ad-72802d44a023, rgb(255, 255, 255))", borderBottomLeftRadius: "80px", borderBottomRightRadius: "80px", borderTopLeftRadius: "80px", borderTopRightRadius: "80px"} as React.CSSProperties}>
<div className="framer-1mc8c0n" data-framer-name="Container"><div className="framer-1p5k9qq" data-framer-name="Text" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "none"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-1bfnqv2" data-styles-preset="w180HGT8R" dir="auto">Download My CV</p></div><div className="framer-kdzsf6" data-framer-name="Text" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", transform: "translateX(-50%)"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-1bfnqv2" data-styles-preset="w180HGT8R" dir="auto">Download My CV</p></div></div><svg className="framer-SYorz framer-1tw0315" role="presentation" viewBox="0 0 24 24" style={{"--1m973uw": "var(--token-73e2668e-ad43-49fd-bc30-9906fc740a6b, rgb(20, 20, 20))", "--js9iwy": "2", transform: "none"} as React.CSSProperties}>
<use href="#1175957644" /></svg></a></div></div></section>
  );
}
