/* eslint-disable @next/next/no-img-element */
/**
 * Lifted verbatim from the Fastfolio template: the same markup and the same
 * class names, so `styles/fastfolio.css` (also taken from the template) lays it
 * out identically. Only the copy, the images and the accent colour differ.
 *
 * Generated — see the lift script in the project notes; edit the data, not this.
 */
export default function SkillsSection() {
  return (
    <section className="framer-1oabbam" data-framer-name="Skills Section" id="skills"><div className="framer-cs5jyx"><div className="framer-x7ytao"><div className="framer-34a4f8-container" data-framer-name="Caption" data-reveal="true"><div className="framer-OLJCl framer-GVdQe framer-1ruw5ua framer-v-1ruw5ua" data-framer-name="Default" style={{backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div className="framer-l21fbl" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-1c49kmm" data-styles-preset="NoguLCmHa" dir="auto">TECH STACK</p></div></div></div><div className="framer-1as8ff9" data-framer-component-type="RichTextContainer"><h2 className="framer-text framer-styles-preset-wj1llc" data-styles-preset="fQF7LPveS" dir="auto" style={{"--framer-text-alignment": "center"} as React.CSSProperties}>
<strong className="framer-text"><span style={{whiteSpace: "nowrap"} as React.CSSProperties}><span style={{display: "inline-block"} as React.CSSProperties} data-char={0}>T</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={1}>o</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={2}>o</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={3}>l</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={4}>s</span></span>{" "}<span style={{whiteSpace: "nowrap"} as React.CSSProperties}><span style={{display: "inline-block"} as React.CSSProperties} data-char={5}>I</span></span>{" "}<span style={{whiteSpace: "nowrap"} as React.CSSProperties}><span style={{display: "inline-block"} as React.CSSProperties} data-char={6}>B</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={7}>u</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={8}>i</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={9}>l</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={10}>d</span></span>{" "}<span style={{whiteSpace: "nowrap"} as React.CSSProperties}><span style={{display: "inline-block"} as React.CSSProperties} data-char={11}>W</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={12}>i</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={13}>t</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={14}>h</span></span></strong></h2></div><div className="framer-y0pdp3" data-framer-component-type="RichTextContainer" data-reveal="true"><p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "center"} as React.CSSProperties}>
The stack I reach for across the whole product — interface, API and data layer</p></div></div><div className="framer-pg84kg" data-framer-name="Skills Grid"><div className="framer-n7e4nv-container" data-framer-name="skill tag" data-reveal="true"><div className="framer-2nqUY framer-bt7oY framer-1d5e8vw framer-v-1d5e8vw" data-border="true" data-framer-name="Default" style={{"--border-bottom-width": "1px", "--border-color": "var(--token-eaa444f4-7e99-47ba-8c71-b1ca35a8422f, rgba(255, 255, 255, 0.05))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div className="framer-isl2zl"><div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="128" height="128" src="/tech/html.svg" alt="HTML5" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "contain"} as React.CSSProperties} />
</div></div><div className="framer-1v7v2bm" data-framer-component-type="RichTextContainer" style={{"--extracted-r6o4lv": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-color": "var(--extracted-r6o4lv, var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255)))"} as React.CSSProperties}>
HTML5</p></div></div></div><div className="framer-1tie526-container" data-framer-name="skill tag" data-reveal="true"><div className="framer-2nqUY framer-bt7oY framer-1d5e8vw framer-v-1d5e8vw" data-border="true" data-framer-name="Default" style={{"--border-bottom-width": "1px", "--border-color": "var(--token-eaa444f4-7e99-47ba-8c71-b1ca35a8422f, rgba(255, 255, 255, 0.05))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div className="framer-isl2zl"><div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="128" height="128" src="/tech/css.svg" alt="CSS3" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "contain"} as React.CSSProperties} />
</div></div><div className="framer-1v7v2bm" data-framer-component-type="RichTextContainer" style={{"--extracted-r6o4lv": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-color": "var(--extracted-r6o4lv, var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255)))"} as React.CSSProperties}>
CSS3</p></div></div></div><div className="framer-gmyxx7-container" data-framer-name="skill tag" data-reveal="true"><div className="framer-2nqUY framer-bt7oY framer-1d5e8vw framer-v-1d5e8vw" data-border="true" data-framer-name="Default" style={{"--border-bottom-width": "1px", "--border-color": "var(--token-eaa444f4-7e99-47ba-8c71-b1ca35a8422f, rgba(255, 255, 255, 0.05))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div className="framer-isl2zl"><div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="58" height="56" src="/tech/javascript.png" alt="JavaScript" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "contain"} as React.CSSProperties} />
</div></div><div className="framer-1v7v2bm" data-framer-component-type="RichTextContainer" style={{"--extracted-r6o4lv": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-color": "var(--extracted-r6o4lv, var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255)))"} as React.CSSProperties}>
JavaScript</p></div></div></div><div className="framer-hwe44t-container" data-framer-name="skill tag" data-reveal="true"><div className="framer-2nqUY framer-bt7oY framer-1d5e8vw framer-v-1d5e8vw" data-border="true" data-framer-name="Default" style={{"--border-bottom-width": "1px", "--border-color": "var(--token-eaa444f4-7e99-47ba-8c71-b1ca35a8422f, rgba(255, 255, 255, 0.05))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div className="framer-isl2zl"><div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="63" height="56" src="/tech/react.png" alt="React" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "contain"} as React.CSSProperties} />
</div></div><div className="framer-1v7v2bm" data-framer-component-type="RichTextContainer" style={{"--extracted-r6o4lv": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-color": "var(--extracted-r6o4lv, var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255)))"} as React.CSSProperties}>
React</p></div></div></div><div className="framer-1dikcdh-container" data-framer-name="skill tag" data-reveal="true"><div className="framer-2nqUY framer-bt7oY framer-1d5e8vw framer-v-1d5e8vw" data-border="true" data-framer-name="Default" style={{"--border-bottom-width": "1px", "--border-color": "var(--token-eaa444f4-7e99-47ba-8c71-b1ca35a8422f, rgba(255, 255, 255, 0.05))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div className="framer-isl2zl"><div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="48" height="48" src="/tech/nextjs.webp" alt="Next.js" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "contain"} as React.CSSProperties} />
</div></div><div className="framer-1v7v2bm" data-framer-component-type="RichTextContainer" style={{"--extracted-r6o4lv": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-color": "var(--extracted-r6o4lv, var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255)))"} as React.CSSProperties}>
Next.js</p></div></div></div><div className="framer-7s4wjz-container" data-framer-name="skill tag" data-reveal="true"><div className="framer-2nqUY framer-bt7oY framer-1d5e8vw framer-v-1d5e8vw" data-border="true" data-framer-name="Default" style={{"--border-bottom-width": "1px", "--border-color": "var(--token-eaa444f4-7e99-47ba-8c71-b1ca35a8422f, rgba(255, 255, 255, 0.05))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div className="framer-isl2zl"><div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="58" height="58" src="/tech/typescript.png" alt="TypeScript" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "contain"} as React.CSSProperties} />
</div></div><div className="framer-1v7v2bm" data-framer-component-type="RichTextContainer" style={{"--extracted-r6o4lv": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-color": "var(--extracted-r6o4lv, var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255)))"} as React.CSSProperties}>
TypeScript</p></div></div></div><div className="framer-tivosj-container" data-framer-name="skill tag" data-reveal="true"><div className="framer-2nqUY framer-bt7oY framer-1d5e8vw framer-v-1d5e8vw" data-border="true" data-framer-name="Default" style={{"--border-bottom-width": "1px", "--border-color": "var(--token-eaa444f4-7e99-47ba-8c71-b1ca35a8422f, rgba(255, 255, 255, 0.05))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div className="framer-isl2zl"><div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="58" height="35" src="/tech/tailwindcss.png" alt="TailwindCSS" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "contain"} as React.CSSProperties} />
</div></div><div className="framer-1v7v2bm" data-framer-component-type="RichTextContainer" style={{"--extracted-r6o4lv": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-color": "var(--extracted-r6o4lv, var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255)))"} as React.CSSProperties}>
TailwindCSS</p></div></div></div><div className="framer-1hx9bgp-container" data-framer-name="skill tag" data-reveal="true"><div className="framer-2nqUY framer-bt7oY framer-1d5e8vw framer-v-1d5e8vw" data-border="true" data-framer-name="Default" style={{"--border-bottom-width": "1px", "--border-color": "var(--token-eaa444f4-7e99-47ba-8c71-b1ca35a8422f, rgba(255, 255, 255, 0.05))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div className="framer-isl2zl"><div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="40" height="40" src="/tech/nodejs.svg" alt="Node.js" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "contain"} as React.CSSProperties} />
</div></div><div className="framer-1v7v2bm" data-framer-component-type="RichTextContainer" style={{"--extracted-r6o4lv": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-color": "var(--extracted-r6o4lv, var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255)))"} as React.CSSProperties}>
Node.js</p></div></div></div><div className="framer-2t3u5x-container" data-framer-name="skill tag" data-reveal="true"><div className="framer-2nqUY framer-bt7oY framer-1d5e8vw framer-v-1d5e8vw" data-border="true" data-framer-name="Default" style={{"--border-bottom-width": "1px", "--border-color": "var(--token-eaa444f4-7e99-47ba-8c71-b1ca35a8422f, rgba(255, 255, 255, 0.05))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div className="framer-isl2zl"><div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="50" height="58" src="/tech/nestjs.svg" alt="NestJS" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "contain"} as React.CSSProperties} />
</div></div><div className="framer-1v7v2bm" data-framer-component-type="RichTextContainer" style={{"--extracted-r6o4lv": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-color": "var(--extracted-r6o4lv, var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255)))"} as React.CSSProperties}>
NestJS</p></div></div></div><div className="framer-zdydcp-container" data-reveal="true"><div className="framer-2nqUY framer-bt7oY framer-1d5e8vw framer-v-1d5e8vw" data-border="true" data-framer-name="Default" style={{"--border-bottom-width": "1px", "--border-color": "var(--token-eaa444f4-7e99-47ba-8c71-b1ca35a8422f, rgba(255, 255, 255, 0.05))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div className="framer-isl2zl"><div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="58" height="58" src="/tech/postgresql.svg" alt="PostgreSQL" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "contain"} as React.CSSProperties} />
</div></div><div className="framer-1v7v2bm" data-framer-component-type="RichTextContainer" style={{"--extracted-r6o4lv": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-color": "var(--extracted-r6o4lv, var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255)))"} as React.CSSProperties}>
PostgreSQL</p></div></div></div><div className="framer-1qvsi3d-container" data-reveal="true"><div className="framer-2nqUY framer-bt7oY framer-1d5e8vw framer-v-1d5e8vw" data-border="true" data-framer-name="Default" style={{"--border-bottom-width": "1px", "--border-color": "var(--token-eaa444f4-7e99-47ba-8c71-b1ca35a8422f, rgba(255, 255, 255, 0.05))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div className="framer-isl2zl"><div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="128" height="128" src="/tech/docker.svg" alt="Docker" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "contain"} as React.CSSProperties} />
</div></div><div className="framer-1v7v2bm" data-framer-component-type="RichTextContainer" style={{"--extracted-r6o4lv": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-color": "var(--extracted-r6o4lv, var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255)))"} as React.CSSProperties}>
Docker</p></div></div></div><div className="framer-13xrn8u-container" data-reveal="true"><div className="framer-2nqUY framer-bt7oY framer-1d5e8vw framer-v-1d5e8vw" data-border="true" data-framer-name="Default" style={{"--border-bottom-width": "1px", "--border-color": "var(--token-eaa444f4-7e99-47ba-8c71-b1ca35a8422f, rgba(255, 255, 255, 0.05))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", backgroundColor: "var(--token-26bc4f1b-0df8-4268-935d-083567ac6888, rgb(20, 20, 20))", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div className="framer-isl2zl"><div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="128" height="128" src="/tech/git.svg" alt="Git" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "contain"} as React.CSSProperties} />
</div></div><div className="framer-1v7v2bm" data-framer-component-type="RichTextContainer" style={{"--extracted-r6o4lv": "var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-color": "var(--extracted-r6o4lv, var(--token-30a1dc7f-21c9-4f57-88cb-ed350becd727, rgb(255, 255, 255)))"} as React.CSSProperties}>
Git</p></div></div></div></div></div></section>
  );
}
