/* eslint-disable @next/next/no-img-element */
/**
 * Lifted verbatim from the Fastfolio template: the same markup and the same
 * class names, so `styles/fastfolio.css` (also taken from the template) lays it
 * out identically. Only the copy, the images and the accent colour differ.
 *
 * Generated — see the lift script in the project notes; edit the data, not this.
 */
export default function TestimonialsSection() {
  return (
    <section className="framer-16qjphs" id="testimonials"><div className="framer-15nrrlf"><div className="framer-1p0ueci"><div className="framer-1h2bbvt-container" data-framer-name="Caption" data-reveal="true"><div className="framer-OLJCl framer-GVdQe framer-1ruw5ua framer-v-1ruw5ua" data-framer-name="Default" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div className="framer-l21fbl" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-1c49kmm" data-styles-preset="NoguLCmHa" dir="auto">TESTIMONIALS</p></div></div></div><div className="framer-96oi42" data-framer-component-type="RichTextContainer"><h2 className="framer-text framer-styles-preset-wj1llc" data-styles-preset="fQF7LPveS" dir="auto" style={{"--framer-text-alignment": "center"} as React.CSSProperties}>
<strong className="framer-text"><span style={{whiteSpace: "nowrap"} as React.CSSProperties}><span style={{display: "inline-block"} as React.CSSProperties} data-char={0}>D</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={1}>o</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={2}>n</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={3}>'</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={4}>t</span></span>{" "}<span style={{whiteSpace: "nowrap"} as React.CSSProperties}><span style={{display: "inline-block"} as React.CSSProperties} data-char={5}>j</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={6}>u</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={7}>s</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={8}>t</span></span>{" "}<span style={{whiteSpace: "nowrap"} as React.CSSProperties}><span style={{display: "inline-block"} as React.CSSProperties} data-char={9}>t</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={10}>a</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={11}>k</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={12}>e</span></span>{" "}<span style={{whiteSpace: "nowrap"} as React.CSSProperties}><span style={{display: "inline-block"} as React.CSSProperties} data-char={13}>m</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={14}>y</span></span>{" "}<span style={{whiteSpace: "nowrap"} as React.CSSProperties}><span style={{display: "inline-block"} as React.CSSProperties} data-char={15}>w</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={16}>o</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={17}>r</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={18}>d</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={19}>s</span></span>{" "}<span style={{whiteSpace: "nowrap"} as React.CSSProperties}><span style={{display: "inline-block"} as React.CSSProperties} data-char={20}>f</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={21}>o</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={22}>r</span></span>{" "}<span style={{whiteSpace: "nowrap"} as React.CSSProperties}><span style={{display: "inline-block"} as React.CSSProperties} data-char={23}>i</span><span style={{display: "inline-block"} as React.CSSProperties} data-char={24}>t</span></span></strong></h2></div><div className="framer-1tdgodn" data-framer-component-type="RichTextContainer" data-reveal="true"><p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto" style={{"--framer-text-alignment": "center"} as React.CSSProperties}>
Words from people who’ve worked with me and experienced my process and results firsthand</p></div></div><div className="framer-1dvfkq6" data-framer-name="Ticker Wrapper"><div className="ssr-variant hidden-2t7pqm"><div className="framer-gq19hk" style={{overflowX: "clip", display: "flex", position: "relative"} as React.CSSProperties}>
<ul role="group" className="ff-ticker__track ff-ticker__track--forward" style={{display: "flex", position: "relative", listStyleType: "none", padding: "0", margin: "0", justifyContent: "flex-start", flexDirection: "row", gap: "20px", alignItems: "center", width: "max-content", height: "100%", maxHeight: "100%", maxWidth: "max-content"} as React.CSSProperties}>
<li className="ticker-item" aria-hidden="false" aria-posinset={1} aria-setsize={1} style={{flexGrow: "0", flexShrink: "0", position: "relative", height: "fit-content", width: "fit-content"} as React.CSSProperties}>
<div className="framer-11wl87s"><div className="framer-163tzzv-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-oqp7up" data-framer-name="Default" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="1680" height="2400" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a2.png" alt="Photo of man smiling" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">Daniel Carter</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Product Designer, Stripe</p></div></div></div><svg className="framer-gS9zB framer-kjv656" role="presentation" viewBox="0 0 24 24" style={{"--1m6trwb": "0", "--21h8s6": "var(--token-214832d9-ac84-4509-9949-47c2926e5da0, rgba(255, 255, 255, 0.4))", "--pgex8v": "1.5"} as React.CSSProperties}>
<use href="#547985882" /></svg></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Working with Nelson was seamless. His attention to detail and ability to translate design into smooth, functional interfaces really stood out.</p></div></div></div><div className="framer-6hddfj-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-oqp7up" data-framer-name="Default" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="1680" height="2400" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a6.png" alt="Photo of man smiling" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">Michael Brown</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">UI/UX Designer, Adobe</p></div></div></div><svg className="framer-gS9zB framer-kjv656" role="presentation" viewBox="0 0 24 24" style={{"--1m6trwb": "0", "--21h8s6": "var(--token-214832d9-ac84-4509-9949-47c2926e5da0, rgba(255, 255, 255, 0.4))", "--pgex8v": "1.5"} as React.CSSProperties}>
<use href="#547985882" /></svg></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">He has a strong eye for design and knows how to bring ideas to life on the web. Collaboration with him is always easy and productive.</p></div></div></div><div className="framer-1nbd9an-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-oqp7up" data-framer-name="Default" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="2400" height="1600" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a5.png" alt="Photo of woman in glasses" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">Emily Watson</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Frontend Developer, Shopify</p></div></div></div><svg className="framer-gS9zB framer-kjv656" role="presentation" viewBox="0 0 24 24" style={{"--1m6trwb": "0", "--21h8s6": "var(--token-214832d9-ac84-4509-9949-47c2926e5da0, rgba(255, 255, 255, 0.4))", "--pgex8v": "1.5"} as React.CSSProperties}>
<use href="#547985882" /></svg></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Nelson writes some of the cleanest code I’ve seen. He’s thoughtful, consistent, and always focused on performance and user experience.</p></div></div></div></div></li><li className="ticker-item" aria-hidden="false" aria-posinset={1} aria-setsize={1} style={{flexGrow: "0", flexShrink: "0", position: "relative", height: "fit-content", width: "fit-content"} as React.CSSProperties}>
<div className="framer-11wl87s"><div className="framer-163tzzv-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-oqp7up" data-framer-name="Default" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="1680" height="2400" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a2.png" alt="Photo of man smiling" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">Daniel Carter</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Product Designer, Stripe</p></div></div></div><svg className="framer-gS9zB framer-kjv656" role="presentation" viewBox="0 0 24 24" style={{"--1m6trwb": "0", "--21h8s6": "var(--token-214832d9-ac84-4509-9949-47c2926e5da0, rgba(255, 255, 255, 0.4))", "--pgex8v": "1.5"} as React.CSSProperties}>
<use href="#547985882" /></svg></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Working with Nelson was seamless. His attention to detail and ability to translate design into smooth, functional interfaces really stood out.</p></div></div></div><div className="framer-6hddfj-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-oqp7up" data-framer-name="Default" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="1680" height="2400" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a6.png" alt="Photo of man smiling" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">Michael Brown</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">UI/UX Designer, Adobe</p></div></div></div><svg className="framer-gS9zB framer-kjv656" role="presentation" viewBox="0 0 24 24" style={{"--1m6trwb": "0", "--21h8s6": "var(--token-214832d9-ac84-4509-9949-47c2926e5da0, rgba(255, 255, 255, 0.4))", "--pgex8v": "1.5"} as React.CSSProperties}>
<use href="#547985882" /></svg></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">He has a strong eye for design and knows how to bring ideas to life on the web. Collaboration with him is always easy and productive.</p></div></div></div><div className="framer-1nbd9an-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-oqp7up" data-framer-name="Default" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="2400" height="1600" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a5.png" alt="Photo of woman in glasses" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">Emily Watson</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Frontend Developer, Shopify</p></div></div></div><svg className="framer-gS9zB framer-kjv656" role="presentation" viewBox="0 0 24 24" style={{"--1m6trwb": "0", "--21h8s6": "var(--token-214832d9-ac84-4509-9949-47c2926e5da0, rgba(255, 255, 255, 0.4))", "--pgex8v": "1.5"} as React.CSSProperties}>
<use href="#547985882" /></svg></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Nelson writes some of the cleanest code I’ve seen. He’s thoughtful, consistent, and always focused on performance and user experience.</p></div></div></div></div></li></ul></div>{" "}</div><div className="ssr-variant hidden-1vo249k hidden-72rtr7"><div className="framer-gq19hk" data-tickereffectalign="center" data-tickereffectdirectionmodifier="default" data-tickereffectgap="20px" data-tickereffecthovermodifier="0" data-tickereffectoverflow="clip" data-tickereffectposition="relative" data-tickereffectstackdirection="row" data-tickereffectvelocity="35">
<div className="framer-11wl87s"><div className="framer-163tzzv-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-1w30umk" data-framer-name="no-quote" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="1680" height="2400" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a2.png" alt="Photo of man smiling" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">Daniel Carter</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Product Designer, Stripe</p></div></div></div></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Working with Nelson was seamless. His attention to detail and ability to translate design into smooth, functional interfaces really stood out.</p></div></div></div><div className="framer-6hddfj-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-1w30umk" data-framer-name="no-quote" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="1680" height="2400" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a6.png" alt="Photo of man smiling" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">Michael Brown</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">UI/UX Designer, Adobe</p></div></div></div></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">He has a strong eye for design and knows how to bring ideas to life on the web. Collaboration with him is always easy and productive.</p></div></div></div><div className="framer-1nbd9an-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-1w30umk" data-framer-name="no-quote" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="2400" height="1600" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a5.png" alt="Photo of woman in glasses" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">Emily Watson</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Frontend Developer, Shopify</p></div></div></div></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Nelson writes some of the cleanest code I’ve seen. He’s thoughtful, consistent, and always focused on performance and user experience.</p></div></div></div></div></div></div><div className="ssr-variant hidden-2t7pqm"><div className="framer-x8ddw2" style={{overflowX: "clip", display: "flex", position: "relative"} as React.CSSProperties}>
<ul role="group" className="ff-ticker__track ff-ticker__track--reverse" style={{display: "flex", position: "relative", listStyleType: "none", padding: "0", margin: "0", justifyContent: "flex-start", flexDirection: "row", gap: "20px", alignItems: "center", width: "max-content", height: "100%", maxHeight: "100%", maxWidth: "max-content"} as React.CSSProperties}>
<li className="ticker-item" aria-hidden="false" aria-posinset={1} aria-setsize={1} style={{flexGrow: "0", flexShrink: "0", position: "relative", height: "fit-content", width: "fit-content"} as React.CSSProperties}>
<div className="framer-1qoys6r" data-framer-name="Testimonial Row"><div className="framer-10wmn07-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-oqp7up" data-framer-name="Default" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="2399" height="1358" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a3.png" alt="Photo of woman " style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">Sarah Johnson</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Software Engineer, Microsoft</p></div></div></div><svg className="framer-gS9zB framer-kjv656" role="presentation" viewBox="0 0 24 24" style={{"--1m6trwb": "0", "--21h8s6": "var(--token-214832d9-ac84-4509-9949-47c2926e5da0, rgba(255, 255, 255, 0.4))", "--pgex8v": "1.5"} as React.CSSProperties}>
<use href="#547985882" /></svg></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Nelson is reliable and detail-oriented. He takes feedback well and continuously improves both the product and his workflow.</p></div></div></div><div className="framer-lflfyp-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-oqp7up" data-framer-name="Default" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="1345" height="2400" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a1.png" alt="Photo of man in glasses and heavily clothed" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">James Wilson</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Product Manager, Atlassian</p></div></div></div><svg className="framer-gS9zB framer-kjv656" role="presentation" viewBox="0 0 24 24" style={{"--1m6trwb": "0", "--21h8s6": "var(--token-214832d9-ac84-4509-9949-47c2926e5da0, rgba(255, 255, 255, 0.4))", "--pgex8v": "1.5"} as React.CSSProperties}>
<use href="#547985882" /></svg></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">He understands product thinking, not just code. That makes a big difference when building features that actually matter to users.</p></div></div></div><div className="framer-10l340u-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-oqp7up" data-framer-name="Default" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="1920" height="2400" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a4.png" alt="Photo of woman " style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">Olivia Martinez</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Creative Developer, Webflow</p></div></div></div><svg className="framer-gS9zB framer-kjv656" role="presentation" viewBox="0 0 24 24" style={{"--1m6trwb": "0", "--21h8s6": "var(--token-214832d9-ac84-4509-9949-47c2926e5da0, rgba(255, 255, 255, 0.4))", "--pgex8v": "1.5"} as React.CSSProperties}>
<use href="#547985882" /></svg></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">His work is clean, modern, and polished. He consistently delivers interfaces that feel intuitive and well-crafted.</p></div></div></div></div></li><li className="ticker-item" aria-hidden="false" aria-posinset={1} aria-setsize={1} style={{flexGrow: "0", flexShrink: "0", position: "relative", height: "fit-content", width: "fit-content"} as React.CSSProperties}>
<div className="framer-1qoys6r" data-framer-name="Testimonial Row"><div className="framer-10wmn07-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-oqp7up" data-framer-name="Default" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="2399" height="1358" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a3.png" alt="Photo of woman " style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">Sarah Johnson</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Software Engineer, Microsoft</p></div></div></div><svg className="framer-gS9zB framer-kjv656" role="presentation" viewBox="0 0 24 24" style={{"--1m6trwb": "0", "--21h8s6": "var(--token-214832d9-ac84-4509-9949-47c2926e5da0, rgba(255, 255, 255, 0.4))", "--pgex8v": "1.5"} as React.CSSProperties}>
<use href="#547985882" /></svg></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Nelson is reliable and detail-oriented. He takes feedback well and continuously improves both the product and his workflow.</p></div></div></div><div className="framer-lflfyp-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-oqp7up" data-framer-name="Default" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="1345" height="2400" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a1.png" alt="Photo of man in glasses and heavily clothed" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">James Wilson</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Product Manager, Atlassian</p></div></div></div><svg className="framer-gS9zB framer-kjv656" role="presentation" viewBox="0 0 24 24" style={{"--1m6trwb": "0", "--21h8s6": "var(--token-214832d9-ac84-4509-9949-47c2926e5da0, rgba(255, 255, 255, 0.4))", "--pgex8v": "1.5"} as React.CSSProperties}>
<use href="#547985882" /></svg></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">He understands product thinking, not just code. That makes a big difference when building features that actually matter to users.</p></div></div></div><div className="framer-10l340u-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-oqp7up" data-framer-name="Default" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="1920" height="2400" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a4.png" alt="Photo of woman " style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">Olivia Martinez</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Creative Developer, Webflow</p></div></div></div><svg className="framer-gS9zB framer-kjv656" role="presentation" viewBox="0 0 24 24" style={{"--1m6trwb": "0", "--21h8s6": "var(--token-214832d9-ac84-4509-9949-47c2926e5da0, rgba(255, 255, 255, 0.4))", "--pgex8v": "1.5"} as React.CSSProperties}>
<use href="#547985882" /></svg></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">His work is clean, modern, and polished. He consistently delivers interfaces that feel intuitive and well-crafted.</p></div></div></div></div></li></ul></div>{" "}</div><div className="ssr-variant hidden-1vo249k hidden-72rtr7"><div className="framer-x8ddw2" data-tickereffectalign="center" data-tickereffectdirectionmodifier="reverse" data-tickereffectgap="20px" data-tickereffecthovermodifier="0" data-tickereffectoverflow="clip" data-tickereffectposition="relative" data-tickereffectstackdirection="row" data-tickereffectvelocity="35">
<div className="framer-1qoys6r" data-framer-name="Testimonial Row"><div className="framer-10wmn07-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-1w30umk" data-framer-name="no-quote" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="2399" height="1358" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a3.png" alt="Photo of woman " style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">Sarah Johnson</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Software Engineer, Microsoft</p></div></div></div></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Nelson is reliable and detail-oriented. He takes feedback well and continuously improves both the product and his workflow.</p></div></div></div><div className="framer-lflfyp-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-1w30umk" data-framer-name="no-quote" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="1345" height="2400" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a1.png" alt="Photo of man in glasses and heavily clothed" style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">James Wilson</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Product Manager, Atlassian</p></div></div></div></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">He understands product thinking, not just code. That makes a big difference when building features that actually matter to users.</p></div></div></div><div className="framer-10l340u-container" data-framer-name="testimonial card"><div className="framer-UMIy9 framer-NU0Pm framer-bt7oY framer-oqp7up framer-v-1w30umk" data-framer-name="no-quote" style={{backgroundColor: "var(--token-2585ae86-e120-4353-80b8-1e0378448460, rgb(24, 24, 24))", width: "100%", borderBottomLeftRadius: "16px", borderBottomRightRadius: "16px", borderTopLeftRadius: "16px", borderTopRightRadius: "16px"} as React.CSSProperties}>
<div className="framer-wqzl45" data-framer-name="Content Wrapper"><div className="framer-1nmc65h" data-framer-name="Name + Role Container"><div className="framer-37egje" style={{borderBottomLeftRadius: "100px", borderBottomRightRadius: "100px", borderTopLeftRadius: "100px", borderTopRightRadius: "100px"} as React.CSSProperties}>
<div style={{position: "absolute", borderRadius: "inherit", cornerShape: "inherit", top: "0", right: "0", bottom: "0", left: "0"} as React.CSSProperties} data-framer-background-image-wrapper="true">
<img decoding="async" width="1920" height="2400" sizes="(min-width: 1440px) 48px, (min-width: 810px) and (max-width: 1439.98px) 48px, (max-width: 809.98px) 48px" src="/avatars/a4.png" alt="Photo of woman " style={{display: "block", width: "100%", height: "100%", borderRadius: "inherit", cornerShape: "inherit", objectPosition: "center", objectFit: "cover"} as React.CSSProperties} />
</div></div><div className="framer-x2ig6d"><div className="framer-1a0lmcd" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<h6 className="framer-text framer-styles-preset-19ddgm0" data-styles-preset="NcyXzMhuN" dir="auto">Olivia Martinez</h6></div><div className="framer-1ubwq28" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">Creative Developer, Webflow</p></div></div></div></div><div className="framer-1lrn6ni" data-framer-component-type="RichTextContainer" style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"} as React.CSSProperties}>
<p className="framer-text framer-styles-preset-13u21mt" data-styles-preset="DMtlcsvaj" dir="auto">His work is clean, modern, and polished. He consistently delivers interfaces that feel intuitive and well-crafted.</p></div></div></div></div></div></div></div></div></section>
  );
}
