# -*- coding: utf-8 -*-
"""Build the Devsync stylesheet: filter to what the page uses, swap the accent,
and take out the section that pinned itself to the viewport."""
import re, os, json, html as H

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DS = os.path.join(REPO, '.lift', 'ds')
css = open(os.path.join(DS, 'all.css')).read()
# Framer writes a per-instance <style> for each rolling-text block *inside* the
# markup, HTML-escaped. Those ship with the JSX, so drop them here.
css = re.sub(r'[^}]*\.rolling-text-inner-[A-Za-z0-9]+[^@]*?(?=\n\.|\n@|$)', '', css)
css = H.unescape(css)
page = open(os.path.join(DS, 'page.built.html')).read()

used = set()
for c in re.findall(r'class="([^"]*)"', page):
    used.update(c.split())
print('classes on page:', len(used))

def split_blocks(text):
    out, depth, buf = [], 0, ''
    for ch in text:
        buf += ch
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                out.append(buf.strip()); buf = ''
    if buf.strip():
        out.append(buf.strip())
    return out

CLS = re.compile(r'\.(-?[_a-zA-Z][\w-]*)')
def wanted(sel):
    names = CLS.findall(sel)
    if not names:
        return True                       # element/:root/keyframes rules
    return any(n in used for n in names)

blocks = split_blocks(css)
kept, keyframes = [], []
for b in blocks:
    sel = b[:b.index('{')].strip() if '{' in b else b
    low = sel.lower()
    if low.startswith(('@font-face', '@import', '@charset')):
        kept.append(b); continue
    if low.startswith(('@keyframes', '@-webkit-keyframes')):
        keyframes.append(b); continue
    if low.startswith(('@media', '@supports', '@layer')):
        inner = b[b.index('{') + 1:b.rindex('}')]
        sub = [sb for sb in split_blocks(inner)
               if wanted(sb[:sb.index('{')] if '{' in sb else sb)]
        if sub:
            kept.append(sel + '{\n' + '\n'.join(sub) + '\n}')
        continue
    if wanted(sel):
        kept.append(b)

out = '\n'.join(kept)

# keyframes that survive are the ones something still references
refs = set()
for v in re.findall(r'animation(?:-name)?\s*:\s*([^;}]+)', out):
    for tok in re.split(r'[\s,]+', v.strip()):
        if re.match(r'^[a-zA-Z_-][\w-]*$', tok):
            refs.add(tok)
out += '\n' + '\n'.join(
    b for b in keyframes
    if re.match(r'@(?:-webkit-)?keyframes\s+([\w-]+)', b[:b.index('{')]).group(1) in refs)

# ---- accent: the template's green becomes orange --------------------------
n = 0
for pat, rep in [
    (r'rgb\(\s*122\s*,\s*242\s*,\s*152\s*\)', 'var(--accent)'),
    (r'#7af298', 'var(--accent)'),
    (r'rgba\(\s*153\s*,\s*247\s*,\s*177\s*,\s*([0-9.]+)\s*\)', r'rgba(255, 138, 71, \1)'),
    (r'#99f7b1b0', 'rgba(255, 138, 71, 0.69)'),
    (r'rgba\(\s*83\s*,\s*137\s*,\s*114\s*,\s*([0-9.]+)\s*\)', r'rgba(137, 83, 39, \1)'),
    (r'#538972', '#895327'),   # hero glow, solid form
    (r'#7ddfb4', '#ffb489'),   # light accent tint
]:
    out, c = re.subn(pat, rep, out, flags=re.I)
    n += c
print('accent swaps in css:', n)

# ---- remove the scroll-jacked image band ---------------------------------
# .framer-1gadbee pinned itself for a viewport-height scrub. Unpin it and let
# it size to its content; the ticker inside keeps running on its own.
out, c = re.subn(
    r'(\.framer-1gadbee\s*\{)([^}]*)(\})',
    lambda m: m.group(1) + re.sub(
        r'(position:sticky|top:0|height:100vh)\s*;?', '', m.group(2)
    ).rstrip(';') + ';position:relative;height:min-content;padding:80px 0' + m.group(3),
    out)
print('unpinned scroll-jack rules:', c)

open(os.path.join(REPO, 'styles', 'devsync.css'), 'w').write(
    '/* ===========================================================================\n'
    '   GENERATED by tools/dscss.py — do not edit; edit the script.\n'
    '\n'
    '   Devsync, taken from the template\'s own compiled stylesheet and filtered to\n'
    '   the classes this page actually uses.\n'
    '\n'
    '   Three deliberate edits:\n'
    '     - the green accent (rgb(122,242,152)) is remapped to orange;\n'
    '     - .framer-1gadbee no longer pins to the viewport, so the image band\n'
    '       scrolls with the page instead of scrubbing images under a sticky frame;\n'
    '     - what Framer\'s runtime used to do lives in styles/overrides.css.\n'
    '   =========================================================================== */\n\n'
    + out)
print('bytes:', len(out))
