# -*- coding: utf-8 -*-
"""Convert the prepared Devsync page into one React component per section.

One 865KB component compiles, but the dev server runs out of heap building
source maps for it. Splitting at the page's own top-level blocks keeps each
file workable and makes the sections addressable by name.
"""
import re, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tojsx import convert

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DS = os.path.join(REPO, '.lift', 'ds')
OUT = os.path.join(REPO, 'components', 'devsync')
os.makedirs(OUT, exist_ok=True)
for f in os.listdir(OUT):
    os.remove(os.path.join(OUT, f))

page = open(os.path.join(DS, 'page.built.html'), encoding='utf-8').read()
sprite = open(os.path.join(DS, 'sprite.html'), encoding='utf-8').read()
sprite = re.sub(r'rgb\(\s*122\s*,\s*242\s*,\s*152\s*\)', 'var(--accent)', sprite)

VOID = {'area','base','br','col','embed','hr','img','input','link','meta','param',
        'source','track','wbr','use','path','circle','rect','polygon','stop',
        'ellipse','line','polyline'}
TAG = re.compile(r'<(/?)([a-zA-Z][a-zA-Z0-9:-]*)((?:[^>"\']|"[^"]*"|\'[^\']*\')*?)(/?)>')

def children_of(s, start):
    m = TAG.match(s, start)
    i, depth, child = m.end(), 1, None
    while True:
        t = TAG.search(s, i)
        if not t:
            return
        name, closing, selfc = t.group(2).lower(), t.group(1), t.group(4)
        if name in VOID or selfc:
            if depth == 1:
                yield (t.start(), t.end())
            i = t.end(); continue
        if closing:
            depth -= 1
            if depth == 0:
                return
            if depth == 1 and child is not None:
                yield (child, t.end()); child = None
        else:
            if depth == 1 and child is None:
                child = t.start()
            depth += 1
        i = t.end()

root   = page.find('<div class="framer-R2Reu')
blocks = list(children_of(page, root))
fmroot = list(children_of(page, blocks[3][0]))
main   = list(children_of(page, fmroot[0][0]))

SECTIONS = ['HeroSpacer', 'Hero', 'About', 'Works', 'Service', 'Process',
            'Testimonial', 'Client', 'Blog']

HEAD = '''/* eslint-disable @next/next/no-img-element */
/**
 * Lifted from the Devsync template — its own markup, laid out by its own
 * stylesheet (styles/devsync.css). The copy, images, links and accent colour
 * are Nelson's; the structure is the template's.
 *
 * Generated by the lift script. Edit the script, not this file.
 */
export default function %s() {
  return (
    <>
%s
    </>
  );
}
'''

written = []
def emit(name, html):
    jsx = convert(html).strip()
    open(os.path.join(OUT, name + '.tsx'), 'w').write(HEAD % (name, jsx))
    written.append((name, len(jsx)))

# Devsync's own Testimonial section is not shipped: the Fastfolio section
# "Don't just take my words for it" takes its place.
DROPPED = {'Testimonial'}

for name, (a, b) in zip(SECTIONS, main):
    if name in DROPPED:
        continue
    emit(name, page[a:b])

# chrome
# blocks[1] is the template's "Buy Template For $49" button; it is not shipped.
emit('Nav', page[blocks[0][0]:blocks[0][1]])
emit('Footer', page[blocks[6][0]:blocks[6][1]])
emit('Sprite', sprite)

# --------------------------------------------------------------------------
# the page shell: the template's own wrappers, with the sections swapped for
# component elements so the DOM nesting is unchanged
# --------------------------------------------------------------------------
shell = page[root:]
# close off: take everything, then rebuild by slicing around the parts
def open_tag(at):
    return TAG.match(page, at).group(0)

parts = []
parts.append(convert(open_tag(root)))                       # .framer-R2Reu
parts.append('<Nav />')
parts.append(convert(page[blocks[2][0]:blocks[2][1]]))      # inline <style>
parts.append(convert(open_tag(blocks[3][0])))               # data-framer-root
parts.append(convert(open_tag(fmroot[0][0])))               # <main>
parts.append('<FastfolioSprite />')
# The three Fastfolio sections slot in among the Devsync ones. Devsync's own
# Testimonial section is dropped: "Don't just take my words for it" replaces it.
FASTFOLIO = {
    'About':   'SkillsSection',       # Tools I Build With
    'Service': 'ExperienceSection',   # Where I've Worked
    'Process': 'TestimonialsSection', # Don't just take my words for it
}
for name in SECTIONS:
    if name == 'Testimonial':
        continue
    parts.append('<%s />' % name)
    if name in FASTFOLIO:
        parts.append('<LiftedScope><%s /></LiftedScope>' % FASTFOLIO[name])
parts.append('</main>')
parts.append('</div>')
parts.append(convert(page[blocks[4][0]:blocks[4][1]]))      # #overlay
parts.append(convert(page[blocks[5][0]:blocks[5][1]]))      # .framer-ik1xi8
parts.append('<Footer />')
parts.append('</div>')

imports = '\n'.join(
    ['import %s from "./%s";' % (n, n)
     for n in SECTIONS + ['Nav', 'Footer'] if n != 'Testimonial']
    + ['import LiftedScope from "../lifted/LiftedScope";',
       'import FastfolioSprite from "../lifted/Sprite";']
    + ['import %s from "../lifted/%s";' % (c, c) for c in FASTFOLIO.values()])
body = '''/**
 * The Devsync page shell: the template's own wrapper elements, with each
 * section rendered by its own component so the DOM nesting is unchanged.
 */
%s

export default function DevsyncPage() {
  return (
%s
  );
}
''' % (imports, '\n'.join('    ' + p for p in parts))
open(os.path.join(OUT, 'DevsyncPage.tsx'), 'w').write(body)

for n, l in written:
    print('%-14s %8d' % (n, l))
print('shell', len(body))
