# -*- coding: utf-8 -*-
"""Build styles/fastfolio.css from the three lifted Fastfolio sections."""
import re, os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FF = os.path.join(REPO, '.lift', 'ff')

HEADER = """/* ===========================================================================
   GENERATED by tools/ffcss.py — do not edit; edit the script.

   "Tools I Build With", "Where I've Worked" and "Don't just take my words for
   it", taken straight from the Fastfolio template's compiled stylesheet so
   those three sections lay out exactly as they do there.

   :root and body rules are dropped so they cannot fight app/base.css.
   =========================================================================== */

"""

def split_blocks(text):
    out, depth, buf = [], 0, ''
    for ch in text:
        buf += ch
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                out.append(buf.strip()); buf = ''
    if buf.strip():
        out.append(buf.strip())
    return out

css = open(os.path.join(FF, 'sections.css')).read()
kept = []
for b in split_blocks(css):
    sel = b[:b.index('{')].strip() if '{' in b else b
    if sel in (':root', 'body', 'html', 'html, body', '*'):
        continue
    kept.append(b)

out = '\n'.join(kept)
open(os.path.join(REPO, 'styles', 'fastfolio.css'), 'w').write(HEADER + out)
print('styles/fastfolio.css', len(out))
