# -*- coding: utf-8 -*-
"""Rebuild the Tools I Build With grid from content/tools.json.

The template ships twelve fixed chips; the grid is regenerated by cloning one
chip per tool so the list is not capped by the template.
"""
import json
import os
import re

from htmlutil import element_at, children_of, retext, plain

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHIP_MARK = 'data-framer-name="skill tag"'


def load_tools():
    with open(os.path.join(REPO, 'content', 'tools.json')) as f:
        return json.load(f)


def rebuild(html):
    tools = load_tools()
    i = html.find(CHIP_MARK)
    if i < 0:
        print('  tools grid: no chips found')
        return html

    grid = html.rfind('<div', 0, html.rfind('<div', 0, i))
    while True:
        span = element_at(html, grid)
        if span and html[span[0]:span[1]].count(CHIP_MARK) > 1:
            break
        nxt = html.rfind('<div', 0, grid)
        if nxt < 0:
            print('  tools grid: no container found')
            return html
        grid = nxt

    chips = list(children_of(html, grid))
    sources = [html[a:b] for a, b in chips]

    out = []
    for n, tool in enumerate(tools):
        src = sources[n % len(sources)]
        label = plain(re.search(r'<p[^>]*>(.*?)</p>', src, re.S).group(1))
        chip, _ = retext(src, {label: tool['label']})
        chip = re.sub(r'src="/tech/[^"]*"', 'src="%s"' % tool['icon'], chip)
        chip = re.sub(r'\salt="[^"]*"', ' alt="%s"' % tool['label'], chip)
        out.append(chip)

    print('  tools grid rebuilt:', len(sources), '->', len(tools), 'chips')
    return html[:chips[0][0]] + ''.join(out) + html[chips[-1][1]:]
