# -*- coding: utf-8 -*-
"""Rebuild the Works grid from content/projects.json.

The template ships six cards; the grid is regenerated by cloning one card per
project, so the number of projects is not capped by the template. Framer emits
a card once per breakpoint, so the repeating unit is (children / template
cards) children wide.
"""
import json
import os
import re

from htmlutil import element_at, children_of, retext, plain

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CARD_MARK = '<div class="framer-arqlo2-container">'
TEMPLATE_CARDS = 6


def load_projects():
    with open(os.path.join(REPO, 'content', 'projects.json')) as f:
        return json.load(f)


def _grids(page):
    """Every element that directly holds more than one project card."""
    found, seen, i = [], set(), 0
    while True:
        j = page.find(CARD_MARK, i)
        if j < 0:
            break
        k = j
        while True:
            k = page.rfind('<div', 0, k)
            if k < 0:
                break
            span = element_at(page, k)
            if not span or span[2] < j:
                continue
            if page[span[0]:span[1]].count(CARD_MARK) > 1:
                if k not in seen:
                    seen.add(k)
                    found.append((k, span))
                break
        i = j + 1
    return found


def _card_fields(page, a, b):
    """The title, description and tags currently in one card unit."""
    unit = page[a:b]
    texts = []
    for m in re.finditer(r'<(h3|p)\b[^>]*>(.*?)</\1>', unit, re.S):
        t = plain(m.group(2))
        if t and t not in texts:
            texts.append(t)
    return texts


def rebuild(page):
    projects = load_projects()
    rebuilt = 0

    for start, span in reversed(_grids(page)):
        children = list(children_of(page, start))
        per_card = len(children) // TEMPLATE_CARDS
        if per_card < 1 or len(children) % TEMPLATE_CARDS:
            continue

        units = [children[i * per_card:(i + 1) * per_card]
                 for i in range(TEMPLATE_CARDS)]
        sources = [page[u[0][0]:u[-1][1]] for u in units]
        fields = [_card_fields(page, u[0][0], u[-1][1]) for u in units]

        out = []
        for i, project in enumerate(projects):
            src = sources[i % TEMPLATE_CARDS]
            old = fields[i % TEMPLATE_CARDS]
            mapping = {}
            if old:
                mapping[old[0]] = project['title']
            if len(old) > 1:
                mapping[old[1]] = project['description']
            for slot, tag in zip(old[2:5], project['tags']):
                mapping[slot] = tag

            card, _ = retext(src, mapping)
            card = re.sub(r'src="/ds/[^"]*"',
                          'src="/projects/%s.webp"' % project['image'], card)
            # the template's img carries a bare alt, its own decoding hint and
            # intrinsic dimensions that no longer describe this file
            card = re.sub(
                r'\s(?:alt(?:="[^"]*")?|loading="[^"]*"|decoding="[^"]*"'
                r'|width="[^"]*"|height="[^"]*")(?=[\s>])', '', card)
            card = card.replace(
                '<img ',
                '<img loading="lazy" decoding="async" '
                'alt="%s screenshot" ' % project['title'].replace('"', ''))
            card = re.sub(r'href="[^"]*"', 'href="%s"' % project['href'], card)
            out.append(card)

        page = page[:children[0][0]] + ''.join(out) + page[children[-1][1]:]
        rebuilt += 1

    print('works grids rebuilt:', rebuilt, 'with', len(projects), 'projects')
    return page
